fos_rest:
    body_listener: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', stop: true }
    param_fetcher_listener: true
    routing_loader:
        include_format: false
    serializer:
        serialize_null: true
    service:
        inflector: App\ApiInflector
    view:
        view_response_listener: 'force'
        formats:
            html: true
            json: true
